### ISSUE TITLE
Tyler

### ISSUE THREAD

**Issue by kryllyxofficial01** [Tukeque/Plattyler#1]
Just a suggestion, but I highly recommend making Tyler a pip library. That way when people want to use it, they just do `pip install tyler` and the needed stuff is available. This would be better than having them copy and paste the `tyler.py` file every time they want to use it.

**Comment by Tukeque** [comment]
Yeah, I've thought of it but i don't know how to upload a library to pip and also didn't expect it to get used. Also Tyler is still missing some features I need to add and I'm currently doing other projects, but I'll think about uploading it. Thanks for your suggestion

**Comment by kryllyxofficial01** [comment]
There are two ways to do it: poetry and twine. Poetry is more complex to set up, but it gives you more features. Twine is simpler, but you're more limited. I personally recommend twine, as it is good for starting out. The links for both are below:

twine:
https://twine.readthedocs.io/en/stable/

poetry:
https://python-poetry.org/docs/

Also good luck with Tyler. It is a really cool concept.
